apiVersion: v1
kind: Service
metadata:
  name: todoapp
  labels:
    name: todoapp
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    name: todoapp
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: todoapp
  name: todoapp
spec:
  replicas: 2
  selector:
    name: todoapp
  template:
    metadata:
      labels:
        name: todoapp
    spec:
      containers:
      - image: edevregille/todoapp
        name: todoapp
        ports:
        - containerPort: 8888
          name: http-server
        env:
          - name: NEW_RELIC_LICENSE_KEY 
            value: "ADD_YOUR_LICENSE_KEY"            
          - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
            value: "true"
          - name: MONGO_SERVICE_HOST
            value: "mongo"
